[user-account]
; 配置账号密码，留空则打开网页后手动登录
username = 
password = 

[browser-option]
; 配置浏览器，可选 Edge|Chrome
driver = Edge
; 指定浏览器所在路径，不填则使用默认路径
EXE_PATH =

[script-option]
; 是否自动隐藏浏览器窗口(默认:False)
enableHideWindow = False
; 母页无未满蓝条节次时的重扫间隔/秒
scanInterval = 15
; 最大并行窗口/任务数
parallelTasks = 3
; 实时状态/OCR输出间隔/秒
statusInterval = 5

[course-option]
; 限制单次锁定某一节的观看时长/min (不限制:0)
limitMaxTime = 30
; 限定播放倍速 (最高:1.8)
limitSpeed = 1.8
; 设置是否静音播放 (默认:True)
soundOff = True

[course-url]
; 配置要学习的课程链接
; 可继续添加多个课程链接
URL1 = 
URL2 =
URL3 =
URL4 =
URLn =
